import type { CaseStatus, PriorityLevel } from "@/types/database";

export type DemoCase = { id: string; case_number: number; title: string; description: string; status: CaseStatus; priority: PriorityLevel; client: string; company: string; department: string; assignee: string; updated_at: string; created_at: string; requires_approval: boolean; requires_human: boolean };

export const demoCases: DemoCase[] = [
  { id: "demo-184", case_number: 184, title: "Autorización de propuesta comercial", description: "El cliente solicita una autorización comercial con un límite de tiempo inferior a 48 horas.", status: "waiting_approval", priority: "urgent", client: "Mariana López", company: "ABC Corporation", department: "Comercial", assignee: "Responsable asignado", updated_at: new Date(Date.now() - 8 * 60000).toISOString(), created_at: new Date(Date.now() - 2 * 3600000).toISOString(), requires_approval: true, requires_human: true },
  { id: "demo-183", case_number: 183, title: "Incidencia en entrega internacional", description: "Seguimiento de documentación para despacho aduanal.", status: "waiting_human", priority: "high", client: "Carlos Méndez", company: "Norte Logistics", department: "Operaciones", assignee: "Responsable asignado", updated_at: new Date(Date.now() - 42 * 60000).toISOString(), created_at: new Date(Date.now() - 4 * 3600000).toISOString(), requires_approval: false, requires_human: true },
  { id: "demo-182", case_number: 182, title: "Confirmación de condiciones de servicio", description: "El cliente espera confirmación de las nuevas condiciones.", status: "follow_up", priority: "normal", client: "Sofía Ramírez", company: "Grupo Delta", department: "Customer Success", assignee: "Responsable asignado", updated_at: new Date(Date.now() - 3 * 3600000).toISOString(), created_at: new Date(Date.now() - 28 * 3600000).toISOString(), requires_approval: false, requires_human: false },
  { id: "demo-181", case_number: 181, title: "Revisión de contrato marco", description: "Revisión final del contrato marco para firma.", status: "waiting_verification", priority: "high", client: "Andrés Torres", company: "Vértice SA", department: "Legal", assignee: "Responsable asignado", updated_at: new Date(Date.now() - 5 * 3600000).toISOString(), created_at: new Date(Date.now() - 2 * 86400000).toISOString(), requires_approval: false, requires_human: true },
  { id: "demo-180", case_number: 180, title: "Solicitud de actualización de cuenta", description: "Actualización de datos fiscales solicitada por el cliente.", status: "in_progress", priority: "normal", client: "Lucía Herrera", company: "Atlas Trading", department: "Administración", assignee: "Responsable asignado", updated_at: new Date(Date.now() - 24 * 3600000).toISOString(), created_at: new Date(Date.now() - 3 * 86400000).toISOString(), requires_approval: false, requires_human: false },
];

export const workflows = [
  ["PE01", "Outlook Intake", "success", "hace 2 min", "1,284"], ["PE02", "Evaluate", "success", "hace 2 min", "1,281"], ["PE03", "Reply Orchestrator", "success", "hace 4 min", "987"], ["PE04", "Approval Router", "success", "hace 8 min", "412"], ["PE05", "Case Classifier", "success", "hace 9 min", "1,274"], ["PE06", "Customer Context", "success", "hace 12 min", "849"], ["PE07", "Follow-up Scheduler", "success", "hace 15 min", "290"], ["PE08", "Delegation Manager", "success", "hace 18 min", "156"], ["PE09", "Audit Logger", "success", "hace 20 min", "2,840"], ["PE10", "Delivery Retry", "failed", "hace 23 min", "92"], ["PE11", "Escalation", "success", "hace 31 min", "64"], ["PE12", "Daily Digest", "success", "ayer", "28"],
] as const;
