-- Decision Engine boundary: business authority is persisted separately from execution.
alter table public.actions add column if not exists decision_id uuid;
alter table public.workflow_executions add column if not exists workflow_code text;
alter table public.workflow_executions add column if not exists decision_id uuid;
alter table public.workflow_executions add column if not exists command_id uuid;

create table if not exists public.authority_decisions (
    id uuid primary key default gen_random_uuid(),
    organization_id uuid not null references public.organizations(id) on delete cascade,
    action_id uuid references public.actions(id) on delete set null,
    case_id uuid references public.cases(id) on delete set null,
    conversation_id uuid references public.conversations(id) on delete set null,
    decision text not null,
    action_type text not null,
    authorized boolean not null,
    requires_approval boolean not null default false,
    reason text not null,
    rule text,
    rule_version text,
    playbook_version text,
    evidence jsonb not null default '{}'::jsonb,
    expected_version integer,
    correlation_id uuid,
    idempotency_key text not null unique,
    created_at timestamptz not null default now()
);

create table if not exists public.commands (
    id uuid primary key default gen_random_uuid(),
    organization_id uuid not null references public.organizations(id) on delete cascade,
    action_id uuid references public.actions(id) on delete set null,
    decision_id uuid not null references public.authority_decisions(id) on delete restrict,
    workflow_code text not null,
    command_type text not null,
    payload jsonb not null default '{}'::jsonb,
    status text not null default 'created',
    idempotency_key text not null unique,
    created_at timestamptz not null default now()
);

alter table public.actions
    add constraint actions_decision_fk
    foreign key (decision_id) references public.authority_decisions(id) on delete set null;

alter table public.workflow_executions
    add constraint workflow_executions_decision_fk
    foreign key (decision_id) references public.authority_decisions(id) on delete set null;

alter table public.workflow_executions
    add constraint workflow_executions_command_fk
    foreign key (command_id) references public.commands(id) on delete set null;

alter table public.authority_decisions enable row level security;
alter table public.commands enable row level security;

create index if not exists authority_decisions_case_idx
on public.authority_decisions(organization_id, case_id, created_at desc);

create index if not exists commands_action_idx
on public.commands(organization_id, action_id);

create policy authority_decisions_select
on public.authority_decisions
for select to authenticated
using (organization_id = public.current_user_organization_id());

create policy commands_select
on public.commands
for select to authenticated
using (organization_id = public.current_user_organization_id());


comment on table public.authority_decisions is 'Business decisions returned by the Decision Engine; not generated by UI, n8n or AI.';
comment on table public.commands is 'Authorized commands that n8n may execute.';
